# Generated by Django 2.1 on 2020-01-24 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cofe.Drink')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('drinks', models.ManyToManyField(through='cofe.Sale', to='cofe.Drink')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='s_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cofe.Worker'),
        ),
    ]
